version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4010:4010"
    environment:
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=4010
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4080:4080"
    restart: always
